language: rust
sudo: true

matrix:
  include:
    - os: osx
      rust: nightly
    - rust: nightly
      before_script:
        - sudo apt-get install libgmp-dev -y
        - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH


script:
  - PATH=/home/travis/bin:$PATH cargo test -vv
