language: rust
sudo: true

matrix:
  include:
    - os: osx
      rust: nightly
    - rust: nightly
      before_script:
        - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5


script:
  - PATH=/home/travis/bin:$PATH cargo test -vv
